### ISSUE TITLE
Templated pages not displaying content on Netlify deploy due to URL lowercasing

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1046]
## Steps To Reproduce

See this URL: https://deploy-preview-1045--evidence-development-workspace.netlify.app/templated-pages/

And click any of the rows in the table
![CleanShot 2023-07-17 at 17 48 11](https://github.com/evidence-dev/evidence/assets/12602440/22a7322b-4950-43e5-beaa-366dd17cb5e3)

### Environment

- OS: Mac
- Browser: All
- Database: duckdb

## Expected Behavior

Templated page should load as expected

## Actual Behaviour

Actual content flashes briefly before being replaced by error messages for empty components. Title of the page becomes unformatted (appears in lower case).

## Workarounds

None

**Comment by ud3sh** [comment]
@ItsMeBrianD @csjh @hughess 
I suspect this is another case of the duckdb driver doesn't load correctly (likely due to missing library on linux)

We are masking these errors as `missing database credentials` on each query.
https://github.com/evidence-dev/evidence/blob/4872e0f57e658730ea1d264f26132f210f7577c5/packages/db-orchestrator/index.cjs#L71

In this case, the query would be broken, and therefore you'd see empty charts etc.

**Comment by csjh** [comment]
Yeah, if it was a DuckDB issue then the Query Viewers wouldn’t have data loaded in them

**Comment by archiewood** [comment]
Couldn't have been caused by this?

https://github.com/evidence-dev/evidence/pull/846

**Comment by archiewood** [comment]
see https://github.com/evidence-dev/evidence/issues/691 where we had this issue before

**Comment by archiewood** [comment]
Maybe the "solution" here is to call it out in the docs:

https://docs.evidence.dev/deployment/netlify

We can add an admonisment warning similar to the one we have in vercel about duckDB
