### ISSUE TITLE
Weird sorting in BarChart

### ISSUE THREAD

**Issue by yhoiseth** [evidence-dev/evidence#115]
(Screenshots are deliberately low on detail due to confidentiality reasons. As always, I can show things on a call if desired.)

I have a query that is sorted the way I want to. In DataTable, this works fine — it is sorted by the second-to-last column:

```jsx
<DataTable
    data={data.my_query}
    rows={1000}
/>
```

<img width="575" alt="Screenshot 2021-09-01 at 16 29 52" src="https://user-images.githubusercontent.com/8469540/131690838-e03404d7-a384-49ab-82c3-877b1de74164.png">

However, with BarChart, the sorting is off:

```jsx
<BarChart 
    data={data.my_query} 
    x=name
    y=y
/>
```

<img width="269" alt="Screenshot 2021-09-01 at 16 36 56" src="https://user-images.githubusercontent.com/8469540/131691211-64fad6dc-c16d-4265-8028-3f4cd9c019ad.png">

I don’t understand what it’s sorting on. It’s not on the X value, and not on the Y value.

Setting `sort={false}` kind of works, but the sort is in the wrong direction:

```jsx
<BarChart 
    data={data.my_query} 
    x=name
    y=y
    sort={false}
/>
```

<img width="506" alt="Screenshot 2021-09-01 at 16 42 07" src="https://user-images.githubusercontent.com/8469540/131692025-e2852519-cb6c-4fc9-ad36-b154868ac5f6.png">

The same goes for `sort={true}`.

**Comment by hughess** [comment]
@yhoiseth by default, if the x-axis is categorical, the bar chart should sort the y column descending. I'm not sure what it's doing for the sort in your first chart. Do you have time today for a quick call to debug?

At the moment, the bar chart treats the bottom of the chart as the highest value - we'll need to fix that. If you're curious, the reason it does that is because of the pixel position of each element in the chart (further down the page = higher y-coordinate). We'll change the sorting so it matches what you would expect based on your query!

As a workaround until that's fixed, using `ASC` instead of `DESC` in your query will get you the right sort order in your bar chart.

**Comment by yhoiseth** [comment]
Thanks. Don’t have more time today (am in Europe), will hopefully get to check it out tomorrow.

**Comment by hughess** [comment]
Sounds great! I'll play around with the sorting and see what's going on

**Comment by yhoiseth** [comment]
I’m going to look into this now. Available for debugging for approximately the next couple of hours.

**Comment by hughess** [comment]
After debugging, confirmed that sort issue in bar and column charts is caused by duplicate labels on the x-axis. Chart component loops through each distinct item on the x-axis, so multiple entries will be overlapped (multiple bars drawn on top of each other). The first entry in the table for each x-axis label determines the order of the bars, then the other bars are drawn overtop.

Ideally, the chart would print the data exactly as it is inputted, but given that this shouldn't be a common scenario, won't put this as a priority to fix.
