### ISSUE TITLE
Support for ClickHouse database connector

### ISSUE THREAD

**Issue by emakarov** [evidence-dev/evidence#1237]
## Feature Description
What would you like to see added to Evidence?
A: ClickHouse database connector

## Goal of Feature
Ability to use ClickHouse as a backend

## Current Solution / Workarounds
Use other BI tools

**Comment by archiewood** [comment]
You _should_ be able to use the Postgres connector to connect to ClickHouse.

Give it a whirl and lmk if you have any issues!

**Comment by archiewood** [comment]
See also: https://github.com/evidence-dev/evidence/issues/515

**Comment by emakarov** [comment]
yes, clickhouse has both mysql and postgres protocols but not sure if connectors support all the clickhouse-specific sql queries?

**Comment by emakarov** [comment]
also, at this moment, or at least several months ago these protocols were not available in clickhouse-cloud

**Comment by archiewood** [comment]
Don't currently have a clickhouse instance so can't test, but we pass the SQL unedited straight to the engine, so I would imagine anything that works, works!

**Comment by emakarov** [comment]
Haven't deep dive into your connectors code but noticed some type-related converters. Need to notice clickhouse has some specific types, at least. Which do not exist in Postgres, for example.

**Comment by archiewood** [comment]
Aha didn't realize ClickHouse had specific types.

Okay, going to leave this open for now!

**Comment by archiewood** [comment]
Hello - looping back on connector requests

We have recently re-architected Evidence (since this issue was opened), and Evidence is now "pluggable", meaning you can write your own connectors, publish them, and use them in Evidence.

If you are interesting in writing a connector, here are some resources:

1. Docs on creating a plugin: https://docs.evidence.dev/plugins/creating-a-plugin/datasources
2. Template for a connector plugin: https://github.com/evidence-dev/datasource-template
3. An example that I spun up for pulling stats from the npm API: https://github.com/archiewood/npm-stats

If you do write a plugin:

- the suggested package name is `evidence-connector-[plugin]`
- the docs are new, so let us know if there is extra information you need
- share it on the Evidence [community](https://github.com/evidence-dev/evidence/issues/slack.evidence.dev), and we'll feature it!
