### ISSUE TITLE
Box Plots

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1251]
[See slack](https://evidencedev.slack.com/archives/C023MMFSWKU/p1696983025751809)

> I'd like to show A/B test results with confidence intervals, which would require box plots as a component type, similar to what's showing in this article.

https://www.sama.com/blog/experiment-driven-development-part-3/

**Comment by hughess** [comment]
There's a few ways we can set this up - the chart could accept pre-calculated data to create the boxes (i.e. you pass in the min, max, ranges yourself) or the chart can calculate everything when you pass in a series of numbers.

If we go with the latter, there's an ECharts utility function called `prepareBoxplotData` shown in this example here:
https://codepen.io/sjcobb/pen/GwYvKP

**Comment by hughess** [comment]
I've been able to pull together a very rough initial box plot component with hardcoded data:
<img width="579" alt="CleanShot 2023-10-11 at 09 02 13@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/ed6ae7b3-657d-4267-8b28-a0241eb83050">

## Implementation Challenges
- Importing the `prepareBoxplotData` function from `echarts` - I keep getting errors on this - either "not a function" or "cannot use import outside of a module"
- Handling horizontal vs. vertical orientation with `swapXY` - this will take some extra thinking since the data structure is different from a normal chart
- Passing group names to the x-axis is difficult

**Comment by mcrascal** [comment]
> the chart could accept pre-calculated data to create the boxes (i.e. you pass in the min, max, ranges yourself) or the chart can calculate everything when you pass in a series of numbers.

my 2c. 

I think supplying their own ranges for statistical significance is probably preferable to start, despite being a slightly worse interface. 

1. You don't have to use the standard IQR, you can use whatever indication of significance they want. 
2. You can pass in a small table, rather than pushing a large table + a client side JS calculation. 

I think post #993 we could do the IQR calc in ddb/arrow performantly on a fairly large table, and offer it up as an option, but that's easier to add _at some point_ if we start w/ a component that just creates the boxplot from the range arguments.
