### ISSUE TITLE
Universal SQL: Handle sparse source tables

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1270]
## Steps To Reproduce

Running `@usql` 

Querying a bigquery table w/ a column containing only nulls, or mostly nulls, throws zod complaining of a mismatch to expected schema. This doesn't happen in cases where a single value is null, so my suspicion is a whole pagination block includes nulls. 

## Expected Behaviour

Nulls returned matching source table.

**Comment by mcrascal** [comment]
Similar issue occurring in CSVs, see [slack](https://evidencedev.slack.com/archives/C05HS4806NT/p1697101520029969)

**Comment by csjh** [comment]
Can't reproduce w/ `SELECT CAST(null AS STRING) AS col UNION ALL SELECT CAST(null AS STRING) AS col UNION ALL SELECT CAST(null AS STRING) AS col;`, could've possibly been a mismatch in versions causing the generator function (from #1215) to have been rejected because it isn't an array (as expected in pre-#1215 versions)?

**Comment by mcrascal** [comment]
Confirmed all good
