### ISSUE TITLE
InfluxDB database connector

### ISSUE THREAD

**Issue by ianchanning** [evidence-dev/evidence#1518]
## What do you use this database for?

This is our primary data store for all our time series measurements from various IoT devices. Whether it be temperature, humidity or light.

## Are there any popular and well-maintained clients for this database?

- https://www.npmjs.com/package/@influxdata/influxdb-client (v2)
- https://www.npmjs.com/package/@influxdata/influxdb3-client (v3)

## Are you interested in contributing this database connector?

It's kind of chicken and egg. Not currently as we're not using evidence yet, but if we start integrating evidence for other datasources we'd be keen to contribute to getting this up and running.

**Comment by archiewood** [comment]
There is a start on InfluxDB here: https://github.com/evidence-dev/datasources

**Comment by archiewood** [comment]
It's not maintained, more a POC, but may provide a jumping off if combined with the datasource template

**Comment by ianchanning** [comment]
So am I correct that the current datasource `https://github.com/evidence-dev/datasources/blob/main/influxdb/index.mjs` is assuming that you pass in a flux query?

**Comment by archiewood** [comment]
Yes, it assumes you have `.flux` files in your `sources/my_flux_datasource` directory

**Comment by archiewood** [comment]
Hello -looping back on connector requests

We have recently re-architected Evidence (since this issue was opened), and Evidence is now "pluggable", meaning you can write your own connectors, publish them, and use them in Evidence.

If you are interesting in writing a connector, here are some resources:

1. Docs on creating a plugin: https://docs.evidence.dev/plugins/creating-a-plugin/datasources
2. Template for a connector plugin: https://github.com/evidence-dev/datasource-template
3. An example that I spun up for pulling stats from the npm API: https://github.com/archiewood/npm-stats

If you do write a plugin:

- the suggested package name is `evidence-connector-[plugin]`
- the docs are new, so let us know if there is extra information you need
- share it on the Evidence [community](https://github.com/evidence-dev/evidence/issues/slack.evidence.dev), and we'll feature it!
