### ISSUE TITLE
multiselect - consider more defaultValue options including none or many.

### ISSUE THREAD

**Issue by natepixel** [evidence-dev/evidence#1792]
## Feature Description

When you enable "multiple" on the dropdown the defaultValue selects the first item. There are many cases where you might want to instead select a discrete set, or select all, or select none. I propose expanding options for defaultValue to support this.

## Goal of Feature

My use case is a "State filter" dropdown. If nothing is selected, then no filter value is passed, and my SQL responds by showing all states. If a set of states is selected, it uses those states in the SQL.

## Current Solution / Workarounds

If after the page loads I click the "Clear Selection" link at the bottom of the multi-select, it accomplishes my goal. There isn't a way to have this be the default state though.

## Alternatives

Having everything selected by default could also work for my purpose - though I think ideally you could have nothing selected, everything selected, or a discrete set of options.

**Comment by gnaryak** [comment]
Thanks for writing this up, @natepixel! I need this also. My specific use case is multi-selecting tags that are optionally associated with users. Since some users have no tags, I'd want the default state to be "none selected". In that case, I would not filter by tag at all. In any case, I think that my situation would be addressed nicely by your proposed improvement to Evidence. Thanks!

**Comment by archiewood** [comment]
A paying customer just asked for this feature
