### ISSUE TITLE
DateRange: Unable to select larger range after making a selection & auto end-range decrement

### ISSUE THREAD

**Issue by AyushAgrawal-A2** [evidence-dev/evidence#1892]
## Steps To Reproduce
Using following query in example-project
![image](https://github.com/evidence-dev/evidence/assets/54364088/d3edf5b2-12e9-4f03-9f17-4e16acec9d3a)

### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.5.0
- OS: Windows 11 x64
- Browser: Chrome 123.0.6312.122
- Database: example-project's needful_things.orders

## Expected Behavior
- End range date should not auto decrement
- I should to able to select a larger date range, irrespective of previous selection

## Actual Behaviour
- End range auto decrements (this is locale specific, error in `dateToYYYYMMDD` function for some locale, mine is UTC+5:30)

https://github.com/evidence-dev/evidence/assets/54364088/ee846730-4be2-4ce3-a2cc-87eea38c51f7

- Only the selected range is active, unable to select outside of previous selection (screencast after fixing date autodecrement issue)

https://github.com/evidence-dev/evidence/assets/54364088/f4d17ae3-e08c-43ee-8311-3d95ce5ff607

## Workarounds
Use a secondary query that is not filtered by the daterange, to drive the daterange (same as #1875 )

**Comment by ItsMeBrianD** [comment]
Here is what is happening:
 - The query evaluates with "all time" as the bounds
 - The input gets the min/max dates from your query, and modifies the `start` and `end` values internally (because they haven't been set externally), to scope the values to the query
 - Each time you make a selection, the query gets trimmed down, and the above step repeats itself, until you are left with only one date.

The noted workaround is the correct answer in this case, there is an example of this in the [docs](https://docs.evidence.dev/components/date-range/#filtering-a-query). Alternatively, you can use the `start` and `end` props to manually set the range of selectable dates.

Here is an example of how both of the usages would work:

    ```sql sales_unbounded
    select
      date_trunc('week', order_datetime) AS week,
      sum(sales) AS total_sales
    from needful_things.orders
    group by 1
    order by 1
    ```


    ```sql sales_bounded
    select * FROM ${sales_unbounded}
    where week between '${inputs.date_range.start}' and '${inputs.date_range.end}'
    ```

    
    <DateRange name=date_range data={sales_unbounded} dates=week/>

    <DataTable data={sales_bounded} />

    
    <DateRange name=date_range_manual data={sales_unbounded} dates=week start={new Date(0)} end={new Date()}/>
