### ISSUE TITLE
Out of memory during build

### ISSUE THREAD

**Issue by zachstence** [evidence-dev/evidence#2282]

**Comment by hughess** [comment]
Happens when running `npm run build` - will get a `JavaScript heap out of memory` error in the terminal

![CleanShot 2024-07-29 at 12 06 23@2x](https://github.com/user-attachments/assets/2f3d35fa-c992-4662-8e95-1ba3fcdf0b9d)


Workaround is to add this to the command to increase the memory: `NODE_OPTIONS="--max-old-space-size=4096`

@archiewood has a theory that it might be related to the MermaidJS library, as the memory issues in deployments/builds started showing up around that time

**Comment by zachstence** [comment]
This is also happening in our new E2E tests in macOS when building a project created from the Evidence template (with a couple small pages added)

https://github.com/evidence-dev/evidence/actions/runs/10169332555/job/28125994939

**Comment by zachstence** [comment]
Things I have tried without noticeable success
- Upgrading TypeScript to v5.5.4 to get this fix: https://github.com/microsoft/TypeScript/pull/58398
- Using this Vite plugin to not generate sourcemaps for `node_modules/`: https://github.com/vitejs/vite/issues/2433#issuecomment-1487472995

**Comment by zachstence** [comment]
Some relevant information from Rollup (used by Vite under the hood): https://rollupjs.org/troubleshooting/#error-javascript-heap-out-of-memory

**Comment by archiewood** [comment]
any thoughts on ripping out the (undocumented, AFAIK unused) mermaidJS lib and the component it uses
