### ISSUE TITLE
[Bug]: Snowflake OCSP based Certificated Revocation Logs 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#2527]
### Describe the bug

Snowflake connector prints an unpleasant warning on each tick of a `run-sources` into the console. 

`fail open` is the default behaviour for their node driver. Ideally our connector could avoid triggering this warning, but at the very least we should catch it and present it in a way that doesn't disrupt the console feedback on a sources run. 

```
◣ Processing...{"level":"WARN","message":"[2:11:03.504 PM]: WARNING!!! using fail-open to connect. Driver is connecting to an HTTPS endpoint without OCSP based Certificated Revocation checking as it could not obtain a valid OCSP Response to use from the CA OCSP responder. Details: Error:  not found in AuthorityInfoAccess"
  source.sql" 

```

### Steps to Reproduce

Run sources with snowflake 

### Severity

serious, but I can work around it

**Comment by archiewood** [comment]
I have investigated somewhat here.

Snowlake claim to have fixed this as of v1.6.21, but we are at 1.9.0 and still getting the warnings

https://github.com/snowflakedb/snowflake-connector-nodejs/pull/457

I am able to upgrade to 1.9.3, and the warnings are still appearing

However, unable to upgrade >1.10.0 because there appears to be some kind of breaking change

(but nothing mentioned in the [release notes](https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2024#version-1-10-0-february-27-2024))

```
Unable to perform operation because a connection was never established.
```

Latest is 1.14.X, which also cannot upgrade to, for the same reason as 1.10.0
