### ISSUE TITLE
Settings: Set project title

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#256]
> When I make a report with excel, it doesn't say excel all over it. 
> - Unnamed CFO

- Add an option in the dev mode settings to replace the top-left title with your organization/ project name.  
- Store these settings in a config file that can be checked into version control

**Comment by mcrascal** [comment]
See discussion on #308, to revisit soon.

**Comment by antaresjhw** [comment]
I'd like to add another vote in support of this feature.

From a UX perspective, It's not clear what the word "Evidence" means at the top-left, since my users don't know what technology underlies the reports they are viewing. It links to the index page, or the "main" report of course, but that isn't intuitive from the name. I believe that most users expect the topmost item on a menu like this to be the home page, and while the link behavior reflects this the name does not make it clear.

A few approaches I could see working in my use case:
  - Use the `title` frontmatter value on index.md, if it exists. As pointed out elsewhere, some effort to keep the label from overflowing might be needed, although wrapping perhaps isn't the worst solution
  - Allow configuring a project name, as done with #308 
  - Using the string "Home", as a fallback

I see the value in branding a page as an "Evidence" project, but that might work better as something in the footer of the sidebar.  For example, the phrase "Powered by [Evidence](https://www.evidence.dev)" above the settings link could be stronger branding for Evidence, while still allowing the home link label to be customized.

This is a great project that I am having a lot of fun with, and which I believe will prove valuable at my company as well. These are just my opinions as I have started to use this, I hope the perspective is valuable.

**Comment by archiewood** [comment]
Added in https://github.com/evidence-dev/evidence/pull/1637
