### ISSUE TITLE
Ensure client side navigation when following a rowlink in a table

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#2565]
Row links leverage window.location, this leads to no pre-fectching and poor loading experience. 

https://github.com/evidence-dev/evidence/blob/951a7aa3fcf336d2b16aa3a06a78d81fc66eeb27/packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte#L27

**Comment by zachstence** [comment]
@mcrascal I'd like to take a deeper dive into how we implement table row links.

After some googling, it seems clickable table rows are somewhat of an antipattern because:
- Its not easily accessible
  - Without an `<a>`, screenreaders don't know its clickable (our current problem)
  - An `<a>` tag must go in a table cell, so we either have only one cell clickable, or a bunch of anchors for every cell
- With `<a>` tags, the text is no longer highlightable for copy/paste, which seems very useful for a `DataTable`

---

I think the direction I'd like to go is having a dedicated column for the link:

#### Either an automatically added one:

```jsx
<DataTable
  data={[
    {
      country: "United States",
      population: 333300000,
      wikiLink: "https://en.wikipedia.org/wiki/United_States",
    },
    {
      country: "Mexico",
      population: 127500000,
      wikiLink: "https://en.wikipedia.org/wiki/Mexico",
    },
    {
      country: "Canada",
      population: 38930000,
      wikiLink: "https://en.wikipedia.org/wiki/Canada",
    },
  ]}
  link="wikiLink"
/>
```

| Country | Population | |
| --- | --- | --- |
| United States | 333,300,000 | [See more](https://en.wikipedia.org/wiki/United_States) |
| Mexico | 127,500,000 | [See more](https://en.wikipedia.org/wiki/Mexico) |
| Canada | 38,930,000 | [See more](https://en.wikipedia.org/wiki/Canada) |

#### Or user-specified:
```jsx
<DataTable
  data={[
    {
      country: "United States",
      population: 333300000,
      wikiLink: "https://en.wikipedia.org/wiki/United_States",
    },
    {
      country: "Mexico",
      population: 127500000,
      wikiLink: "https://en.wikipedia.org/wiki/Mexico",
    },
    {
      country: "Canada",
      population: 38930000,
      wikiLink: "https://en.wikipedia.org/wiki/Canada",
    },
  ]}
>
  <Column id="country" title="Country" link="wikiLink" />
  <Column id="population" title="Population" />
</DataTable>
```

| Country | Population |
| --- | --- |
| [United States](https://en.wikipedia.org/wiki/United_States) | 333,300,000 |
| [Mexico](https://en.wikipedia.org/wiki/Mexico) | 127,500,000 |
| [Canada](https://en.wikipedia.org/wiki/Canada) | 38,930,000 |

What do you think?

**Comment by zachstence** [comment]
Relevant blog post: https://adrianroselli.com/2020/02/block-links-cards-clickable-regions-etc.html#Update02

**Comment by mcrascal** [comment]
That pattern is already achievable with the link content type. 

We already offer clickable rows, and users seem to prefer them over turning the first column into a link. 

If it'd help with accessibility, I'd be open to adding a chevron type of indicator in a final column when rows are clickable, with screen reader text as the link target, but I don't think we can get away from offering the clickable row. 

Alternatively, if we don't want to wrap things in an a tag, could we look into how to trigger svelte kit's pre-fetching behaviour on hover of table row.

**Comment by archiewood** [comment]
This implementation seems very good to me:

https://codepen.io/aardrian/pen/dyorWwr
