### ISSUE TITLE
Snowflake TIMESTAMP_TZ type not working as expected

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#388]
**Bug Description**
- When using a snowflake TIMESTAMP_TZ column, the date did not display correctly unless cast to a date.
- Instead it displayed each of the dates as 1900-01-00 (which is not even a valid date)

**Expected Behavior**
To display the date as in snowflake

**Error Messages and Screenshots**
![image](https://user-images.githubusercontent.com/58074498/186531517-8bca6856-a241-4c58-98f6-cd2b88f9cfe2.png)

![image](https://user-images.githubusercontent.com/58074498/186531548-82b4ccc6-0522-4438-9410-d1d9cab620ba.png)

**Workarounds**
- Cast to datetime manually: `datetime_column::datetime`

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [x] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite

**Comment by hughess** [comment]
@archiewood which browser were you in when you saw this? 

I'm getting different results when I try to run across browsers:

### Chrome
<img width="617" alt="CleanShot 2022-09-15 at 15 06 53@2x" src="https://user-images.githubusercontent.com/12602440/190488636-70f6c121-f043-4378-8455-5732d3fdab7b.png">

### Safari
<img width="593" alt="CleanShot 2022-09-15 at 15 07 06@2x" src="https://user-images.githubusercontent.com/12602440/190488656-9b5cc51a-49d3-4345-993d-bd6f2f614787.png">

### Firefox
<img width="590" alt="CleanShot 2022-09-15 at 15 07 12@2x" src="https://user-images.githubusercontent.com/12602440/190488677-6c563124-6fcf-49f6-80b9-f327e4c3d438.png">

**Comment by archiewood** [comment]
Hmm I'm not sure - most likely firefox.

Looks most similar to the Safari one though...

**Comment by hughess** [comment]
Thanks. It looks like this issue is actually caused by the browser. I wrote a query to test the different timestamp types in Snowflake and I've gotten different results across browsers:

### Chrome
Works with everything
<img width="589" alt="CleanShot 2022-09-15 at 15 54 26@2x" src="https://user-images.githubusercontent.com/12602440/190496841-73da1173-14c9-4e3c-9db5-97aa6b08fdd9.png">

### Safari
Doesn't like any of the timestamps
<img width="680" alt="CleanShot 2022-09-15 at 15 54 38@2x" src="https://user-images.githubusercontent.com/12602440/190496852-3b41440a-a81f-43d9-ad47-00276d75174b.png">

### Firefox
Doesn't like timestamp_tz or _ltz
<img width="587" alt="CleanShot 2022-09-15 at 15 54 46@2x" src="https://user-images.githubusercontent.com/12602440/190496871-75ec9787-d6ab-4515-b0ad-3638b3faf701.png">

**Comment by hughess** [comment]
Update on this - I've modified the date parsing function to attempt to get all date inputs into a standardized format. So far so good: Snowflake dates are now working in all 3 of these browsers.

### Chrome
<img width="678" alt="CleanShot 2022-10-04 at 15 23 04@2x" src="https://user-images.githubusercontent.com/12602440/193907899-4209ff7a-581e-4125-adbe-9ba1cbd408fa.png">

### Safari
<img width="680" alt="CleanShot 2022-10-04 at 15 23 17@2x" src="https://user-images.githubusercontent.com/12602440/193907916-f6198d8e-a1f9-4134-bd0a-7e48c7e30dd3.png">

### Firefox
<img width="585" alt="CleanShot 2022-10-04 at 15 23 29@2x" src="https://user-images.githubusercontent.com/12602440/193907941-3045e786-8be1-4275-aa7d-43858ba2bf16.png">

## Remaining Issues
The last problem is the chart axes produced by `Chart.svelte`. ECharts is apparently not able to handle the Snowflake timezone dates.

#### Here's a timestamp without a timezone:
<img width="690" alt="CleanShot 2022-10-04 at 15 26 11@2x" src="https://user-images.githubusercontent.com/12602440/193908318-712012fa-b22d-4e61-a7dc-ae92440dc113.png">

#### And here's one with a timezone:
<img width="680" alt="CleanShot 2022-10-04 at 15 26 15@2x" src="https://user-images.githubusercontent.com/12602440/193908328-264a0b2f-bbfd-4f09-b407-3df77dc66ea7.png">

This is a problem within `Chart`, so it affects all browsers equally.
