### ISSUE TITLE
`init: must be run as PID 1` when running via docker-in-docker in a devcontainer

### ISSUE THREAD

**Issue by aaronsteers** [evidence-dev/evidence#439]
I'm seeing an error 

`init: must be run as PID 1`

When run in Codespaces with docker-in-docker feature and the image `evidencedev/devenv:latest`. Is there a reason why `init` wants PID 1?

Log:

```
@aaronsteers ➜ /workspaces/meltano-demo-in-a-box/analyze (evidence-dev ✗) $ meltano invoke --containers evidence:init
2022-10-26T05:36:36.975058Z [info     ] Environment 'dev' is active
2022-10-26T05:36:37.278228Z [info     ] Running command in container   container_name=meltano-evidence--init-690b254b-ffa3-463d-a2be-b4de0a7b77f0
2022-10-26T05:36:38.065090Z [info     ] Starting Evidence.dev development environment mounted on /evidence-workspace in the container.
2022-10-26T05:36:38.065273Z [info     ] Provided arguments => init
2022-10-26T05:36:38.065362Z [info     ] Running command => init
2022-10-26T05:36:38.065441Z [info     ] init: must be run as PID 1
```

**Comment by ud3sh** [comment]
@aaronsteers 

I am guessing you intend on running the `--init` in the Evidence Docker image [bootstrap.sh script](https://github.com/evidence-dev/docker-devenv/blob/main/bootstrap.sh).

It seems to me that with your setup, the bootstrap script receives `init` as argument instead of `--init`.

When the bootstrap script doesn't finding a matching argument (i.e `--init`) it will simply execute the argument you provided it as a command.  In your case, the script ends up executing the `init` process (`/sbin/init` .... this is a linux process unrelated to evidence  which if I run in isolation, will emit `init: must be run as PID 1`, see below).   I bet if you replace your `init` argument with `ls` in your setup, `ls` would get executed at the end.  
 
My suggestion would be to replace `init` with `--init` in your setup.  If this doesn't work, if you can provide me with some setup instructions I could take a closer look.

```
#Output I got by bashing into an Evidence docker container and trying to run `init`
bash-5.1# which init
/sbin/init
bash-5.1# init
init: must be run as PID 1
```

**Comment by aaronsteers** [comment]
Hi, @ud3sh. Thanks for the quick reply! Yes, as you suggest: I was passing `init` instead of `--init`. Changing to `--init` resolved my issue. 🙌
