### ISSUE TITLE
CSS from settings page leaking into components in client-side navigation

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#455]
**Bug Description**
If you navigate from the Settings page to a regular markdown page using client-side navigation, some CSS from the settings page takes precedence over component-specific styling on the markdown page. The issue does not appear a page refresh or when using server-side navigation.

**Severity**
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
CSS from Settings page shouldn't impact components on other pages.

**Steps To Reproduce**
1. Start on a page that has a query on it - open the query viewer data table and look at the data scrubber
2. Navigate to the Settings page using client-side navigation
3. Navigate back to the previous page by clicking the page link in the sidebar
4. The scrubber in the query viewer will now appear with a grey border and it will be in a slightly lower position

![CleanShot 2022-11-10 at 21 17 28](https://user-images.githubusercontent.com/12602440/201248128-a6609ff9-f7a1-4014-b314-a7b9c2872674.gif)

**Info for Potential Solution**
- The formatting applied (e.g., the grey border in the data scrubber example) is coming from the `format-grid.css` file in the `src/components/ui/Formatting` directory
- If I comment out the formatting in that file and repeat the steps to reproduce above, the issue disappears
- It's not clear to me how the styling is getting applied

**Comment by quoid** [comment]
You may have already come to this conclusion, but...

The app is importing `format-grid.css` into a few different components [[1](https://github.com/evidence-dev/evidence/blob/25596b3c20a0a6677a4f8707db9f9e284a15014e/sites/example-project/src/components/ui/Formatting/CurrencyFormatGrid.svelte#L2), [2](https://github.com/evidence-dev/evidence/blob/25596b3c20a0a6677a4f8707db9f9e284a15014e/sites/example-project/src/components/ui/Formatting/CustomFormatGrid.svelte#L2), [3](https://github.com/evidence-dev/evidence/blob/25596b3c20a0a6677a4f8707db9f9e284a15014e/sites/example-project/src/components/ui/Formatting/BuiltInFormatGrid.svelte#L2)]. Those components get loaded by [`Sidebar.svelte`](https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/components/ui/Sidebar.svelte) and when they do, the imported css get loaded into the `head` inside of a `<style>` tag. It's not scoped to those components, it's global.

From what I can tell, in `dev` mode, the app is using client side routing, so when you visit a subsequent page, those injected `<style>` tags (from `format-grid.css`) aren't flushed. I am not sure if we should expect them to be flushed or not, but I've encountered this before.

The quick way to fix this is to add `config.kit.router: false` in the `svelte.config.js` file. This option is not longer documented in the [SvelteKit config docs](https://kit.svelte.dev/docs/configuration), but it [used to be](https://github.com/sveltejs/kit/blob/%40sveltejs/kit%401.0.0-next.268/documentation/docs/11-page-options.md#router) and it is seemingly still valid. This will disable client side routing which may or may not be the desired outcome. However, I tested this locally in `dev` mode and it stopped "leaking" the styles. I did not test this elsewhere.

The more involved, and better fix, is to not import global styles into components and if you must, name-space those styles. Ideally the only place global styles get imported is in the `layout` file or `app.html/css`. An even better solution, *might be* to create a `FormatGrid` component with some props, rather than having `BuiltInFormatGrid`, `CurrencyFormatGrid` and `CustomFormatGrid`; and put that style code in there so it is properly scope to that component.

**Comment by hughess** [comment]
Thanks @quoid! We need to keep client-side nav turned on, but the last solution you mentioned seems like it will work well.

@ud3sh is there any issue if we move the CSS from `format-grid.css` into each of the 3 components mentioned above? I've tested it and it solves this issue, but would just result in some duplicated CSS across those components.
