### ISSUE TITLE
 Is there any mechanism to control the update of the chart?

### ISSUE THREAD

**Issue by hooopo** [evidence-dev/evidence#534]
I want to know how the charts queried from the database are refreshed when the data source changes. Is there any mechanism to control the update of the chart?

**Comment by archiewood** [comment]
Hey,

The data refreshes differently based on when you are in **dev** mode vs when you are in **prod**.

Dev
- Queries run live, and then are cached for 15 mins, if you rerun after 15 mins, then the data will be refreshed. 
- We are working on more fine grained controls for caching so that you can have queries always run live, or cache for longer etc.

Prod
- Evidence deployed after a build process. This build process runs all the queries, and then deploys the evidence site.
- So the data is as recent as the most recent build.
- Depending on your use case, you could have evidence rebuild:
   - On a schedule
   - Based on when you make changes to your source data - eg when you merge a change to the code modelling your source data, it triggers an evidence rebuild

Scheduling and rebuilding on merge, and PR preview sites are features included in Evidence Cloud, which is currently in private alpha!

**Comment by hooopo** [comment]
I get it, thanks.
