### ISSUE TITLE
Changesets SEMVER 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#656]
**Bug Description**
Our peer dependencies set up doesn't play nicely with changesets. This causes major release tags on what should be minor / patch releases.

**Comment by archiewood** [comment]
There seems to be a workaround using the `onlyUpdatePeerDependentsWhenOutOfRange` flag, but I do not fully understand the implications

My understanding so far

- `evidence` has a peerDependency on `components` (and db-orchestrator)
- the reason for peer dependencies is because these two packages are tightly bound
   - ie `components` is a “plugin” package for `evidence`.
   - An older version of `components` will not necessarily work with a newest version of `evidence`, as we may use some features of `components` in `evidence`
- Changesets by default will major bump a package, if one of it’s peerDependencies is minor bumped
   - This is a design decision by them.
   - discussion https://github.com/changesets/changesets/issues/555

**Comment by mcrascal** [comment]
We're going to take another look at this in a timebox. 

Ultimate goal is to have a predictable semver release process on `@evidence-dev/evidence`.
