### ISSUE TITLE
How to integrate Google Analytics or Vercel Analytics? 

### ISSUE THREAD

**Issue by hooopo** [evidence-dev/evidence#657]
I couldn't find any related documentation.

**Comment by archiewood** [comment]
Very interesting. We were just discussing analytics internally.

https://vercel.com/docs/concepts/analytics/audiences/quickstart

Has some info on how to set it up. We have not yet upgraded to Svelte-Kit 1.0 (although we are close!) which means the instructions need to change slightly.

rather than using ˋ+layout.svelte` file, you should use a `__layout.svelte` file inside your `pages` directory.

```
<script>
  import { dev } from '$app/environment';
  import { inject } from '@vercel/analytics';

  inject({ mode: dev ? 'development' : 'production' });

</script>
```

you will probably want to copy the default ˋ__layout.svelte` file as indicated in the docs here: https://docs.evidence.dev/features/advanced/custom-styles-and-themes#page-layout

**Comment by hooopo** [comment]
@archiewood thanks a lot, I will try it.

**Comment by archiewood** [comment]
@hooopo -  closing this for now - feel free to reopen if you need more guidance
