### ISSUE TITLE
Grid Arrangements

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#716]
**Feature Description**
A component for quickly creating "two up" / "three" up chart layouts in line in documents.

Unclear what the most straightforward API is for presenting this. E.g. a single configurable `<Grid cols=N >` or something more specific, like: 

```
<TwoUp> 
  <Chart /> 
  <Chart />
</TwoUP>
```

**Comment by ItsMeBrianD** [comment]
@mcrascal for some additional context do you have a picture / wireframe of what you have in mind here?

**Comment by hughess** [comment]
I've been playing around with a few examples - I think the most common case will be to have 2-3 charts side by side.
<img width="615" alt="CleanShot 2023-04-19 at 19 28 52@2x" src="https://user-images.githubusercontent.com/12602440/233221183-fd32460b-416c-4857-b286-8ee5e564b52a.png">

<img width="620" alt="CleanShot 2023-04-19 at 19 29 20@2x" src="https://user-images.githubusercontent.com/12602440/233221180-087e609d-6ace-4896-a6e3-467ed7d99c92.png">

### Some considerations off the top of my head:
- How should the width of the cells in the grid be set?
   - Split evenly based on number of components in the grid (e.g., 2 charts = 50% width each)
   - Allow components to stretch across multiple grid cells (e.g., you set 3 cell width for your grid, then allocate a chart to the 1st cell and a table to cells 2 and 3. Width of the chart becomes 33% and width of the table becomes 67%)
- Some things we'll need to figure out - the complicated ones can probably wait and get tackled separately from the grid:
   - Charts
      - How should charts behave within a smaller space? I think there are some design decisions to make to avoid having labels overlapping/cutting off - e.g., maybe we add a media query to the charts to turn off certain elements when space is constrained enough
      - We may need to offer more options within chart components to turn off visual elements. Right now, we have options to turn off portions of the axes (e.g., if you had 3 charts side by side and only wanted a y-axis on chart 1, you could use the `yAxisLabels` and `yAxisTitle` props to turn off the y-axis for charts 2 and 3)
      - Legends will need some thinking - long legends are already a UX problem in regular width charts, so this one may be tricky. If you had the same legend in multiple charts and wanted to turn some of them off, the chart height will be affected, so the charts won't line up anymore
   - Should content be allowed to extend beyond the grid container? Should we cut content off, allow scrolling within a grid cell, etc.?
      - My first take here is that we should avoid scrolling within cells by default
      - But there are cases where scrolling may be unavoidable - wide tables come to mind
- If we end up sizing the cells evenly based on the number of components within the grid, we may be able to avoid the concept of a "grid row" entirely - you could just stack grid components on top of each other and you'd know the columns will line up (in this case, this might even be a good argument to name the component something like "Row") 
- Our UI buttons will need some thinking for small spaces (download data, download chart image) - maybe at a small enough width we can drop the text from those buttons and only show the icons, then add the text in a tooltip on hover
- How will grids work with copy/paste?

### Thoughts on syntax
Playing around with some ideas for syntax - just brainstorming here

Assuming a situation where I want a chart to take up 1/3 of the article width and a table to take the other 2/3's - one way to do that:
```html
<Grid>
   <GridCol width="33%">
      <Chart>
   </GridCol>
   <GridCol width="67%">
      <Table>
   </GridCol>
</Grid>
```
This looks a bit messy.

Could the width be somehow set in the components themselves? 

```html
<Row>
   <Chart width="33%">
   <Table width="67%">
</Row>
```
A `width` prop could be generalized to other cases as well - if someone wanted to show a chart at 50% width outside of a grid for example.

#### Grid width
We could also offer the concept of "grid width", where rather than supplying a % as a string, a user could supply a number and the cell width would be determined by the % of the total grid width arguments passed to the grid. For example, if `gridWidth` of component A is 2 and `gridWidth` of component B is 4, then A gets 33% and B gets 67%.

### Trying out removing chart elements
<img width="605" alt="CleanShot 2023-04-19 at 20 08 48@2x" src="https://user-images.githubusercontent.com/12602440/233225232-5ad0b1d0-7ac1-4b9e-9a5f-c60e6186042d.png">
