### ISSUE TITLE
Reduce the size of build artifacts by only creating one data object per templated page 

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#900]
## Steps To Reproduce

1. Create a project with a templated page, that has multiple routes.
2. `npm run build`
3. Inspect the contents of the `build` folder
4. Each route has an identical `__data.json` file

## Expected Behavior

There should be only one data file shipped ideally. Otherwise there is a lot of redundant data in the build artifact.

## Actual Behaviour

There are N `__data.json` files

![image](https://github.com/evidence-dev/evidence/assets/58074498/5c5adfaf-5b51-433b-84d4-6ca2ed0fef6e)

I suspect this also slows down the build process _significantly_, as these build files are made. 

## Workarounds

Have lots of storage space whereever you host

**Comment by csjh** [comment]
I'm thinking a possible workaround would be instead of returning data directly from the server load function, we use a universal load function and make a call to the run query endpoint -- this should allow us to prerender the endpoint a single time instead of prerendering what SvelteKit thinks is a different `load` response N times

**Comment by archiewood** [comment]
@csjh this sounds smart, happy to test or help if I can!
