### ISSUE TITLE
Nav page links not working on build

### ISSUE THREAD

**Issue by mheptinstall** [evidence-dev/evidence#942]
## Steps To Reproduce

```
npx degit evidence-dev/template my-project
cd my-project
npm install
npm run build
```

Opening the build output using VS Code Live Server and clicking the Control Logic link in the nav the page doesn't load

![image](https://github.com/evidence-dev/evidence/assets/10913145/d9b29fe8-bdf5-432e-85c9-131001742efc)

Following the build it also states

> Run `npm run preview` to preview your production build locally

This script doesn't exist.

### Environment

- Node version (`node -v`): v20.3.0
- npm version (`npm -v`): 9.6.7
- OS: Windows 11 22H2
- Browser: Edge 114.0.1823.43
- Database: DuckDB including in template

## Expected Behavior

Control logic should load

## Actual Behaviour

Control logic page doesn't load

**Comment by archiewood** [comment]
Hey @mheptinstall !

> ```
> npx degit evidence-dev/template my-project
> cd my-project
> npm install
> npm run build
> ```
> Opening the build output using VS Code Live Server and clicking the Control Logic link in the nav the page doesn't load

If you want to see how the page looks, you should use `npm run dev` rather than `npm run build`.

- `npm run dev` starts the [development server](https://docs.evidence.dev/guides/installation#start-the-development-server) on localhost. Then you can go to `localhost:3000/control-logic` (or a port other than 3000 if you chose it) and the page will load
- `npm run build` builds the static html files for hosting on a server. If you want to view the built outputs, you need to [host them somewhere](https://docs.evidence.dev/deployment/overview), for example Vercel, Netlify or Evidence Cloud. 


> Run npm run preview to preview your production build locally

Ah, I see that's very confusing. This is automatically generated by `Vite`, which is the underlying development server we use when running Evidence. We actually have not implemented the `npm run preview` command. There's an issue open for it here (#259)


Hope that clears things up!

**Comment by mheptinstall** [comment]
@archiewood thanks for your reply.

Clearly a problem with the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VS Code which I expected would handle a static site without issue
