### ISSUE TITLE
HMR breaks when frontmatter added to markdown file

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#963]
I investigated some full page reloads I was getting when building a new feature and found that the behaviour changed based on the inclusion of frontmatter. I initially thought it might have to do with declaring sources from standalone sql files, but that doesn't appear to be the case:

### Frontmatter + Sources
![CleanShot 2023-06-20 at 12 30 41](https://github.com/evidence-dev/evidence/assets/12602440/06cb0e55-93c1-4bf5-9b97-fa88c18a798b)

### Frontmatter Only
![CleanShot 2023-06-20 at 12 32 00](https://github.com/evidence-dev/evidence/assets/12602440/5fc7496b-695c-4a2e-8812-cc39f5db5243)

### No Frontmatter
![CleanShot 2023-06-20 at 12 33 29](https://github.com/evidence-dev/evidence/assets/12602440/71ea6145-49e5-4bab-bd8f-7b0a46f23675)

**Comment by csjh** [comment]
Appears to be something related to Tailwind freaking out when it sees a `context="module"` script tag with an export in it (which is generated when frontmatter is parsed by mdsvex).

Side note from that: Is there a reason why we're using a standalone frontmatter parser instead of overriding the mdsvex frontmatter? Seems like it was introduced in #710 so @ItsMeBrianD you might have the answer?
